[package]
name = "wishlist"
version = "0.1.0"
authors = ["MetroWind <chris.corsair@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = ">=0.10"
tokio = { version = ">=0.2", features = ["macros"] }
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
warp = ">=0.2"
log = ">=0.4"
stderrlog = ">=0.4"
clap = ">=2.33"
toml = ">=0.5"
